### ISSUE TITLE
500 Internal Server Error in Postman for /search API in Sandbox.

### ISSUE THREAD

**Issue by Nithya-ACAD** [beckn/Unified-Energy-Interface#25]
---
**Name:** P2P Energy Transfer (UEI)
**About:** Communication between the BAP and BPP for the P2P energy transfer using the Sandbox environment using openapi: 3.0.0 Beckn Protocol Core DENT layer 2 config version 1.1.0
**Title:** P2P Energy Transfer
**Labels:** P2P Energy Transfer
---

## Description

When interacting with the sandbox environment using the /search API on postman, an internal server error is consistently encountered. The error trace indicates ENOENT, typically signaling a missing file or configuration on the server side. This issue occurs even when the request body adheres to the expected structure as outlined in the provided YAML file.

The request was authenticated using the Bearer token, which was generated by the sandbox for the user (myself), and it was properly included in the request headers under Authorization as Bearer <token>. However, the issue persists even with proper authentication, suggesting that the issue is likely server-side.

This feature request or bug fix is needed to address this error and ensure that the /search API in the sandbox environment works as intended. It will allow users to test the energy transaction flow seamlessly without server-side errors.

## Goals

- [ ] Investigate the cause of the 500 Internal Server Error.
- [ ] Confirm that the server configuration is correct and no required resources are missing.
- [ ] Fix the ENOENT issue to ensure the API functions correctly.
- [ ] Validate the response flow for the /search API
- [ ] Ensure the sandbox environment is fully operational for API testing.

## Expected Outcome

The /search API should return the expected response (such as available energy units from prosumers) without encountering a 500 Internal Server Error. The API request should be processed successfully in the sandbox environment, and the error should be resolved.

## Acceptance Criteria

- [ ] The /search API no longer returns a 500 Internal Server Error.
- [ ] The request flow adheres to the Beckn protocol and responds according to the structure in the YAML file.
- [ ] The server is properly configured to handle requests without missing resources or configurations.
- [ ] The error ENOENT is resolved.
- [ ] The sandbox environment is fully tested and operation.

## Implementation Details

The implementation will involve reviewing the sandbox server's configuration to identify missing files or misconfigurations causing the ENOENT error. Server logs should be examined for detailed traces of the error. Additionally, the request flow and API endpoints should be validated against the YAML file to ensure alignment. It should be verified that the Bearer token authentication mechanism is functioning correctly, as a valid token is already being used.

## Mockups / Wireframes

N/A (No visual mockups are required as this is related to the server configuration and API flow.)

---

### Product Name

P2P Energy Transfer (UEI)

### Project Name

P2P Energy Transfer Sandbox API Issue

### Organization Name:

UEI

### Domain

Energy Transaction API

### Tech Skills Needed:

- API debugging
- Node.js/Express
- Server Configuration
- API Testing

### Complexity

Medium

### Category

[Bug],[API]

### Sub Category

[API],[Backend],[Maintenance],[Support]

**Comment by faizmagic** [comment]
@emmayank , Please request the team to have a look at this issue, also report on this ticket once the issue is fixed

CC: @bharath-ganapathy

**Comment by vbabuEM** [comment]
@Nithya-ACAD , this repo is primarily for the spec and actually been dormant for sometime. For issues, its better to use the Protocol Server repo or the Beckn-ONIX repo. They are monitored much more often and the chances of your issue getting resolved are higher. Another option is the Beckn Open Collective channel on discord. That is also actively monitored by developers. As I mentioned over the office hours call, please add the request you sent and any logs with the details on the error. That will help them troubleshoot the problem.

**Comment by Nithya-ACAD** [comment]
Okay thank you so much. Posted the issue on the protocol-server with the request and the logs.
